package beans;
// Generated 06.07.2017 21:54:31 by Hibernate Tools 4.3.1



/**
 * TFirmUsers generated by hbm2java
 */
public class TFirmUsers  implements java.io.Serializable {


     private long id;
     private TSprFirm TSprFirm;
     private TSprUsers TSprUsers;

    public TFirmUsers() {
    }

    public TFirmUsers(long id, TSprFirm TSprFirm, TSprUsers TSprUsers) {
       this.id = id;
       this.TSprFirm = TSprFirm;
       this.TSprUsers = TSprUsers;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public TSprFirm getTSprFirm() {
        return this.TSprFirm;
    }
    
    public void setTSprFirm(TSprFirm TSprFirm) {
        this.TSprFirm = TSprFirm;
    }
    public TSprUsers getTSprUsers() {
        return this.TSprUsers;
    }
    
    public void setTSprUsers(TSprUsers TSprUsers) {
        this.TSprUsers = TSprUsers;
    }




}


