package beans;
// Generated 06.07.2017 21:54:31 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TIncidentComment generated by hbm2java
 */
public class TIncidentComment  implements java.io.Serializable {


     private long id;
     private TIncident TIncident;
     private TIncidentComment TIncidentComment;
     private TSprCommentType TSprCommentType;
     private TSprUsers TSprUsers;
     private Date FDateCreated;
     private String FComment;
     private Set TIncidentComments = new HashSet(0);
     private Set TIncidentComments_1 = new HashSet(0);

    public TIncidentComment() {
    }

	
    public TIncidentComment(long id, TIncident TIncident, TSprCommentType TSprCommentType, TSprUsers TSprUsers, Date FDateCreated) {
        this.id = id;
        this.TIncident = TIncident;
        this.TSprCommentType = TSprCommentType;
        this.TSprUsers = TSprUsers;
        this.FDateCreated = FDateCreated;
    }
    public TIncidentComment(long id, TIncident TIncident, TIncidentComment TIncidentComment, TSprCommentType TSprCommentType, TSprUsers TSprUsers, Date FDateCreated, String FComment, Set TIncidentComments, Set TIncidentComments_1) {
       this.id = id;
       this.TIncident = TIncident;
       this.TIncidentComment = TIncidentComment;
       this.TSprCommentType = TSprCommentType;
       this.TSprUsers = TSprUsers;
       this.FDateCreated = FDateCreated;
       this.FComment = FComment;
       this.TIncidentComments = TIncidentComments;
       this.TIncidentComments_1 = TIncidentComments_1;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public TIncident getTIncident() {
        return this.TIncident;
    }
    
    public void setTIncident(TIncident TIncident) {
        this.TIncident = TIncident;
    }
    public TIncidentComment getTIncidentComment() {
        return this.TIncidentComment;
    }
    
    public void setTIncidentComment(TIncidentComment TIncidentComment) {
        this.TIncidentComment = TIncidentComment;
    }
    public TSprCommentType getTSprCommentType() {
        return this.TSprCommentType;
    }
    
    public void setTSprCommentType(TSprCommentType TSprCommentType) {
        this.TSprCommentType = TSprCommentType;
    }
    public TSprUsers getTSprUsers() {
        return this.TSprUsers;
    }
    
    public void setTSprUsers(TSprUsers TSprUsers) {
        this.TSprUsers = TSprUsers;
    }
    public Date getFDateCreated() {
        return this.FDateCreated;
    }
    
    public void setFDateCreated(Date FDateCreated) {
        this.FDateCreated = FDateCreated;
    }
    public String getFComment() {
        return this.FComment;
    }
    
    public void setFComment(String FComment) {
        this.FComment = FComment;
    }
    public Set getTIncidentComments() {
        return this.TIncidentComments;
    }
    
    public void setTIncidentComments(Set TIncidentComments) {
        this.TIncidentComments = TIncidentComments;
    }
    public Set getTIncidentComments_1() {
        return this.TIncidentComments_1;
    }
    
    public void setTIncidentComments_1(Set TIncidentComments_1) {
        this.TIncidentComments_1 = TIncidentComments_1;
    }




}


