package beans;
// Generated 06.07.2017 21:54:31 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TIncident generated by hbm2java
 */
public class TIncident  implements java.io.Serializable {


     private long id;
     private TSprFirm TSprFirm;
     private TSprIncidentStatus TSprIncidentStatus;
     private TSprService TSprService;
     private TSprUsers TSprUsers;
     private Date FDate;
     private String FComment;
     private Date FDateCreated;
     private Set TIncidentComments = new HashSet(0);
     private Set TIncidentComments_1 = new HashSet(0);

    public TIncident() {
    }

	
    public TIncident(long id, TSprFirm TSprFirm, TSprIncidentStatus TSprIncidentStatus, TSprService TSprService, Date FDate, String FComment, Date FDateCreated) {
        this.id = id;
        this.TSprFirm = TSprFirm;
        this.TSprIncidentStatus = TSprIncidentStatus;
        this.TSprService = TSprService;
        this.FDate = FDate;
        this.FComment = FComment;
        this.FDateCreated = FDateCreated;
    }
    public TIncident(long id, TSprFirm TSprFirm, TSprIncidentStatus TSprIncidentStatus, TSprService TSprService, TSprUsers TSprUsers, Date FDate, String FComment, Date FDateCreated, Set TIncidentComments, Set TIncidentComments_1) {
       this.id = id;
       this.TSprFirm = TSprFirm;
       this.TSprIncidentStatus = TSprIncidentStatus;
       this.TSprService = TSprService;
       this.TSprUsers = TSprUsers;
       this.FDate = FDate;
       this.FComment = FComment;
       this.FDateCreated = FDateCreated;
       this.TIncidentComments = TIncidentComments;
       this.TIncidentComments_1 = TIncidentComments_1;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public TSprFirm getTSprFirm() {
        return this.TSprFirm;
    }
    
    public void setTSprFirm(TSprFirm TSprFirm) {
        this.TSprFirm = TSprFirm;
    }
    public TSprIncidentStatus getTSprIncidentStatus() {
        return this.TSprIncidentStatus;
    }
    
    public void setTSprIncidentStatus(TSprIncidentStatus TSprIncidentStatus) {
        this.TSprIncidentStatus = TSprIncidentStatus;
    }
    public TSprService getTSprService() {
        return this.TSprService;
    }
    
    public void setTSprService(TSprService TSprService) {
        this.TSprService = TSprService;
    }
    public TSprUsers getTSprUsers() {
        return this.TSprUsers;
    }
    
    public void setTSprUsers(TSprUsers TSprUsers) {
        this.TSprUsers = TSprUsers;
    }
    public Date getFDate() {
        return this.FDate;
    }
    
    public void setFDate(Date FDate) {
        this.FDate = FDate;
    }
    public String getFComment() {
        return this.FComment;
    }
    
    public void setFComment(String FComment) {
        this.FComment = FComment;
    }
    public Date getFDateCreated() {
        return this.FDateCreated;
    }
    
    public void setFDateCreated(Date FDateCreated) {
        this.FDateCreated = FDateCreated;
    }
    public Set getTIncidentComments() {
        return this.TIncidentComments;
    }
    
    public void setTIncidentComments(Set TIncidentComments) {
        this.TIncidentComments = TIncidentComments;
    }
    public Set getTIncidentComments_1() {
        return this.TIncidentComments_1;
    }
    
    public void setTIncidentComments_1(Set TIncidentComments_1) {
        this.TIncidentComments_1 = TIncidentComments_1;
    }




}


