package beans;
// Generated 06.07.2017 21:54:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TSprService generated by hbm2java
 */
public class TSprService  implements java.io.Serializable {


     private long id;
     private String FName;
     private Set TIncidents = new HashSet(0);
     private Set TIncidents_1 = new HashSet(0);

    public TSprService() {
    }

	
    public TSprService(long id, String FName) {
        this.id = id;
        this.FName = FName;
    }
    public TSprService(long id, String FName, Set TIncidents, Set TIncidents_1) {
       this.id = id;
       this.FName = FName;
       this.TIncidents = TIncidents;
       this.TIncidents_1 = TIncidents_1;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public Set getTIncidents() {
        return this.TIncidents;
    }
    
    public void setTIncidents(Set TIncidents) {
        this.TIncidents = TIncidents;
    }
    public Set getTIncidents_1() {
        return this.TIncidents_1;
    }
    
    public void setTIncidents_1(Set TIncidents_1) {
        this.TIncidents_1 = TIncidents_1;
    }




}


