package beans;
// Generated 06.07.2017 21:54:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TSprCommentType generated by hbm2java
 */
public class TSprCommentType  implements java.io.Serializable {


     private long id;
     private String FName;
     private Set TIncidentComments = new HashSet(0);
     private Set TIncidentComments_1 = new HashSet(0);

    public TSprCommentType() {
    }

	
    public TSprCommentType(long id, String FName) {
        this.id = id;
        this.FName = FName;
    }
    public TSprCommentType(long id, String FName, Set TIncidentComments, Set TIncidentComments_1) {
       this.id = id;
       this.FName = FName;
       this.TIncidentComments = TIncidentComments;
       this.TIncidentComments_1 = TIncidentComments_1;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public Set getTIncidentComments() {
        return this.TIncidentComments;
    }
    
    public void setTIncidentComments(Set TIncidentComments) {
        this.TIncidentComments = TIncidentComments;
    }
    public Set getTIncidentComments_1() {
        return this.TIncidentComments_1;
    }
    
    public void setTIncidentComments_1(Set TIncidentComments_1) {
        this.TIncidentComments_1 = TIncidentComments_1;
    }




}


