package beans;
// Generated 06.07.2017 21:54:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TSprUsers generated by hbm2java
 */
public class TSprUsers  implements java.io.Serializable {


     private long id;
     private String FLogin;
     private String FPass;
     private String FName;
     private Set TFirmUserses = new HashSet(0);
     private Set TIncidents = new HashSet(0);
     private Set TIncidentComments = new HashSet(0);
     private Set TFirmUserses_1 = new HashSet(0);
     private Set TIncidents_1 = new HashSet(0);
     private Set TIncidentComments_1 = new HashSet(0);

    public TSprUsers() {
    }

	
    public TSprUsers(long id, String FLogin, String FPass, String FName) {
        this.id = id;
        this.FLogin = FLogin;
        this.FPass = FPass;
        this.FName = FName;
    }
    public TSprUsers(long id, String FLogin, String FPass, String FName, Set TFirmUserses, Set TIncidents, Set TIncidentComments, Set TFirmUserses_1, Set TIncidents_1, Set TIncidentComments_1) {
       this.id = id;
       this.FLogin = FLogin;
       this.FPass = FPass;
       this.FName = FName;
       this.TFirmUserses = TFirmUserses;
       this.TIncidents = TIncidents;
       this.TIncidentComments = TIncidentComments;
       this.TFirmUserses_1 = TFirmUserses_1;
       this.TIncidents_1 = TIncidents_1;
       this.TIncidentComments_1 = TIncidentComments_1;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFLogin() {
        return this.FLogin;
    }
    
    public void setFLogin(String FLogin) {
        this.FLogin = FLogin;
    }
    public String getFPass() {
        return this.FPass;
    }
    
    public void setFPass(String FPass) {
        this.FPass = FPass;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public Set getTFirmUserses() {
        return this.TFirmUserses;
    }
    
    public void setTFirmUserses(Set TFirmUserses) {
        this.TFirmUserses = TFirmUserses;
    }
    public Set getTIncidents() {
        return this.TIncidents;
    }
    
    public void setTIncidents(Set TIncidents) {
        this.TIncidents = TIncidents;
    }
    public Set getTIncidentComments() {
        return this.TIncidentComments;
    }
    
    public void setTIncidentComments(Set TIncidentComments) {
        this.TIncidentComments = TIncidentComments;
    }
    public Set getTFirmUserses_1() {
        return this.TFirmUserses_1;
    }
    
    public void setTFirmUserses_1(Set TFirmUserses_1) {
        this.TFirmUserses_1 = TFirmUserses_1;
    }
    public Set getTIncidents_1() {
        return this.TIncidents_1;
    }
    
    public void setTIncidents_1(Set TIncidents_1) {
        this.TIncidents_1 = TIncidents_1;
    }
    public Set getTIncidentComments_1() {
        return this.TIncidentComments_1;
    }
    
    public void setTIncidentComments_1(Set TIncidentComments_1) {
        this.TIncidentComments_1 = TIncidentComments_1;
    }




}


