package beans;
// Generated 06.07.2017 21:54:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TSprFirm generated by hbm2java
 */
public class TSprFirm  implements java.io.Serializable {


     private long id;
     private String FName;
     private Set TIncidents = new HashSet(0);
     private Set TIncidents_1 = new HashSet(0);
     private Set TFirmUserses = new HashSet(0);
     private Set TFirmUserses_1 = new HashSet(0);

    public TSprFirm() {
    }

	
    public TSprFirm(long id, String FName) {
        this.id = id;
        this.FName = FName;
    }
    public TSprFirm(long id, String FName, Set TIncidents, Set TIncidents_1, Set TFirmUserses, Set TFirmUserses_1) {
       this.id = id;
       this.FName = FName;
       this.TIncidents = TIncidents;
       this.TIncidents_1 = TIncidents_1;
       this.TFirmUserses = TFirmUserses;
       this.TFirmUserses_1 = TFirmUserses_1;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public Set getTIncidents() {
        return this.TIncidents;
    }
    
    public void setTIncidents(Set TIncidents) {
        this.TIncidents = TIncidents;
    }
    public Set getTIncidents_1() {
        return this.TIncidents_1;
    }
    
    public void setTIncidents_1(Set TIncidents_1) {
        this.TIncidents_1 = TIncidents_1;
    }
    public Set getTFirmUserses() {
        return this.TFirmUserses;
    }
    
    public void setTFirmUserses(Set TFirmUserses) {
        this.TFirmUserses = TFirmUserses;
    }
    public Set getTFirmUserses_1() {
        return this.TFirmUserses_1;
    }
    
    public void setTFirmUserses_1(Set TFirmUserses_1) {
        this.TFirmUserses_1 = TFirmUserses_1;
    }




}


